#:schema node_modules/wrangler/config-schema.json
name = "portfolio-contact"
main = "src/index.ts"
compatibility_date = "2024-10-18"
compatibility_flags = ["nodejs_compat"]

send_email = [
    {name = "SEB", destination_address = "gmohsenfarajollahi@gmail.com"}
]

[observability]
enabled = true

[vars]
NAME = "mohsenfaraj.ir"
SENDER = "contact@mohsenfaraj.ir"
RECIPIENT = "gmohsenfarajollahi@gmail.com"